call plug#begin('~/.vim/plugged')
Plug 'christoomey/vim-tmux-navigator'
Plug 'jiangmiao/auto-pairs'
Plug 'wolverian/minimal'
Plug 'vim-scripts/DrawIt'
call plug#end()

set mouse=a
set termguicolors
syntax on
let mapleader = " "
let maplocalleader = ","

colorscheme minimal
highlight Normal guibg=white

set statusline=%=\ \ \ \ \ ჻\ %f\ \ \ \ \ \ \ \ 
" ⁖
set fillchars+=vert:╽,stl:╼,stlnc:\ 

" File tree
let g:netrw_liststyle=3
let g:netrw_banner=0
highlight netrwCompress term=NONE cterm=NONE gui=NONE ctermfg=black guifg=black
highlight netrwDir      term=NONE cterm=NONE gui=NONE ctermfg=black guifg=black
highlight netrwData	    term=NONE cterm=NONE gui=NONE ctermfg=black guifg=black 
highlight netrwHdr	    term=NONE cterm=NONE,italic gui=NONE guifg=black
highlight netrwLex	    term=NONE cterm=NONE,italic gui=NONE guifg=black
highlight netrwYacc	    term=NONE cterm=NONE,italic gui=NONE guifg=black
highlight netrwLib	    term=NONE cterm=NONE gui=NONE ctermfg=black guifg=black
highlight netrwObj	    term=NONE cterm=NONE gui=NONE ctermfg=black guifg=black
highlight netrwTilde    term=NONE cterm=NONE gui=NONE ctermfg=black guifg=black
highlight netrwTmp	    term=NONE cterm=NONE gui=NONE ctermfg=black guifg=black
highlight netrwTags	    term=NONE cterm=NONE gui=NONE ctermfg=black guifg=black
highlight netrwDoc	    term=NONE cterm=NONE gui=NONE ctermfg=black guifg=black
highlight netrwSymLink  term=NONE cterm=NONE gui=NONE ctermfg=black guifg=black

set listchars=tab:>-,trail:+
set hlsearch
set noshowmatch
let g:loaded_matchparen=1
packadd! matchit

source ~/code/Env/vim/tabline.vim

highlight VertSplit guibg=lightgrey guifg=white
highlight clear StatusLine
highlight clear StatusLineNC
highlight StatusLine guibg=white guifg=white cterm=none
highlight StatusLineNC guibg=white guifg=white cterm=none
highlight Cursor guifg=green
highlight clear CursorLine
highlight CursorLine guibg=white guibg=#F7F7F7
highlight NonText guifg=black
highlight Visual guibg=#FFFFD0
highlight Search guibg=#FFFFD0
set cursorline
au Filetype clojure let b:AutoPairs = {'(':')', '[':']', '{':'}','"':'"', '`':'`'}

augroup BgHighlight
    autocmd!
    autocmd WinEnter * set cul
    autocmd WinLeave * set nocul
augroup END

set tabstop=4
set shiftwidth=4

" finding
set path+=**
set wildmenu
set wildmode=longest,list,full

" undo history, etc
set hidden
set undofile
set undodir=~/.vim/undo
set directory=$HOME/.vim/swapfiles//

" completion
" set omnifunc=syntaxcomplete#Complete
highlight Pmenu  term=NONE cterm=NONE gui=NONE guibg=#FFFFD0 guifg=#F8F8F8 
highlight PmenuSel  term=NONE cterm=NONE gui=NONE,bold,underline guibg=#FFFFD0 guifg=black
setlocal omnifunc=syntaxcomplete#Complete
" see help ft-syntax-omni
if has("autocmd") && exists("+omnifunc")
	autocmd Filetype *
				\	if &omnifunc == "" |
				\		setlocal omnifunc=syntaxcomplete#Complete |
				\	endif
endif
set shortmess+=c
