call plug#begin('~/.vim/plugged')
Plug 'matthias-margush/vim-buftabline'
Plug 'christoomey/vim-tmux-navigator'
Plug 'guns/xterm-color-table.vim'
Plug 'jiangmiao/auto-pairs'
Plug 'junegunn/fzf.vim'
Plug 'scrooloose/nerdtree'
Plug 'wolverian/minimal'
Plug 'vim-scripts/DrawIt'
call plug#end()

set mouse=a
set termguicolors
syntax on
let mapleader = " "
let maplocalleader = ","

colorscheme minimal
highlight Normal guibg=white

source ~/code/Env/vim/navigation.vim

set statusline=%=\ \ \ \ \ ჻\ %f\ \ \ \ \ \ \ \ 
" ⁖
set fillchars+=vert:╽,stl:╼,stlnc:\ 

set listchars=tab:>-,trail:+
set hlsearch
set noshowmatch
let g:loaded_matchparen=1

highlight TabLineFill guifg=white guibg=white cterm=none
highlight TabLineSel guifg=#F9F9F9 guibg=white gui=none cterm=bold,underline
highlight PmenuSel guifg=#F9F9F9 guibg=white gui=none cterm=bold,underline
highlight TabLine guifg=#F9F9F9 guibg=white gui=none cterm=none,underline

highlight VertSplit guibg=lightgrey guifg=white
highlight clear StatusLine
highlight clear StatusLineNC
highlight StatusLine guibg=white guifg=white cterm=none
highlight StatusLineNC guibg=white guifg=white cterm=none
highlight Cursor guifg=green
highlight clear CursorLine
highlight CursorLine guibg=white guibg=#F9F9F9
highlight NonText guifg=black
highlight Visual guibg=#FFFFD0
highlight Search guibg=#FFFFD0
set cursorline
au Filetype clojure let b:AutoPairs = {'(':')', '[':']', '{':'}','"':'"', '`':'`'}

augroup BgHighlight
    autocmd!
    autocmd WinEnter * set cul
    autocmd WinLeave * set nocul
augroup END

set tabstop=4
set shiftwidth=4

" finding
set path+=**
set wildmenu
set wildmode=longest,list,full

" undo history, etc
set hidden
set undofile
set undodir=~/.vim/undo
set directory=$HOME/.vim/swapfiles//
